### ISSUE TITLE
c1a1b is lower than c1a1f

### ISSUE THREAD

**Issue by BloodyBody** [gzalo/HalfMapper#2]
![image](https://cloud.githubusercontent.com/assets/10611357/5814353/cc322f1e-a0b4-11e4-8de4-2f716baec31b.png)

**Comment by gzalo** [comment]
Thanks! I've fixed it manually, the offset seems to be exactly 96 units vertically. Those two levels feature very different textures coordinates, so there is some visible "flickering"/vibration of the textures.
