### ISSUE TITLE
Mouse Issue [SOLVED] and Map Loading Issue

### ISSUE THREAD

**Issue by Hades-Realm** [gzalo/HalfMapper#8]
I try to use the mouse, but it starts to shake randomly and does not work.

**Comment by gzalo** [comment]
Hi! Sorry for the delay. 
Which Operating System are you using? 
Are you using the binary found in my website (inside halfmapper-latest.zip)?
Thanks

**Comment by Hades-Realm** [comment]
I'm using Windows 8.1, and yes, I'm using the latest one.

**Comment by gzalo** [comment]
Okay. Are your graphics drivers updated? Which Graphics card do you have? Have you used any other SDL2 or OpenGL app without any issues?

I will update the binary using the latest libraries today, I'll let you know when I do it.

**Comment by Hades-Realm** [comment]
My drivers are updated to latest, and i use a Nvidia GTX 765M (using a gaming laptop). I've used"OpenSource" (another HL map combiner thing)without problems, maybe it counts as OpenGL or SDL2.

**Comment by gzalo** [comment]
Hi. Sorry for the delay, I've been busy. 
Try this latest build:
http://gzalo.com/downloads/halfmapper-latest.zip

Also, please tell me what FPS is shown in the window title. Thanks!

**Comment by Hades-Realm** [comment]
It does work fine now, thanks. The maps (other than Anomalous Materials and Unforseen Consequences) don't seem to load. I set "render" to 1, but they don't load.

**Comment by gzalo** [comment]
Hi. You need to add the render="1" tag to each individual map (and to the chapter as well). 

I know, its a bit tedious :P

**Comment by gzalo** [comment]
Uploaded: XML for halflife with every map enabled (except for Xen)

[halflife.zip](https://github.com/gzalo/HalfMapper/files/499886/halflife.zip)
